-- create database logitoch;
-- show database logitoch;
drop database varun;
create database varun;
use varun;
CREATE TABLE USERS(
	ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(60) NOT NULL,
    AGE INT NOT NULL,
    PRIMARY KEY(ID)
);
SHOW TABLES;
DESCRIBE USERS;
ALTER TABLE USERS 	ADD GENDER  VARCHAR(8)	NOT NULL ,
					ADD CITY VARCHAR(60) 	NOT NULL ,
                    ADD CONTACT VARCHAR(10)		NOT null ;
ALTER TABLE USERS RENAME  TO STUDENTS;

INSERT INTO STUDENTS VALUES (NULL,'VARUN',78,'MAEL','CHENNAI',947262),
			(NULL,'SARAVANAN',78,'MAEL','CHENNAI',1947262);
INSERT INTO STUDENTS (USERNAME,AGE,GENDER,CITY,CONTACT) VALUES             
			('SAMEER',178,'MAEL','CHENNAI',947262),
            ('yogi',21,'MAEL','CHENNAI',1147262),
            ('boseco',8,'MAEL','CHENNAI',7262),
            ('kalai',178,'MAEL','CHENNAI',947262),
            ('SHAM',18,'MAEL','CHENNAI',947262);
-- DELETE FROM STUDENTS WHERE ID=4;
-- UPDATE STUDENTS SET AGE=3 WHERE ID=3;
-- SELECT MAX(AGE) FROM STUDENTS;	
select * from students
-- SELECT USER_NAME(); 
